jwtSecret = ""

[server]
# "debug"开发模式；"release"生成模式
app_model = "debug"
app_port = ":8888"

[database]
host = ""
port = ""
user = ""
password = ""
db_name = ""

[qiniu]
access_key = "FQVAgztMfryIsmRoJ9qpwHKUny-o88v1KQE6yzUB"
secret_key = "2oY9gzWSx_aBCUZxEK-3KRPxOJcmOVxxlw9aO0DC"
bucket = "macleblog"
qiniu_server = "http://rx46effzx.hn-bkt.clouddn.com/"