jwtSecret = "myJWTSecret"

[server]
# "debug"开发模式；"release"生成模式
app_model = "debug"
app_port = ":8888"

[database]
host = "172.28.96.1"
port = "3306"
user = "mcblog"
password = "123456"
db_name = "mcblog"

[qiniu]
access_key = "2ocAmqRiymamYtbZodP3LJ6XVUO5zqXwymZ6f-fn"
secret_key = "tztWUVS_Pkkz4HWqVvK6n5bShMWJTGChp5fZS2H6"
bucket = "macleblog"
qiniu_server = "http://rx6f35vbs.hn-bkt.clouddn.com/"