jwtSecret = ""

[server]
# "debug"开发模式；"release"生成模式
app_model = "debug"
app_port = ":8888"

[database]
host = "172.28.96.1"
port = "3306"
user = "mcblog"
password = "123456"
db_name = "mcblog"

[qiniu]
access_key = "IwThxYMPEv97Z5-BcYGWpp3ftGatklH9kl0Wc-fu"
secret_key = "5vNGKdKzbRQjR0yneHICL44aHOs-3UZYELeIxJII"
bucket = "macleblog"
qiniu_server = "https://qiniu.macleliu.com"
