jwtSecret = "myJWTSecret"

[server]
# "debug"开发模式；"release"生成模式
app_model = "debug"
app_port = ":8888"

[database]
host = "172.28.96.1"
port = "3306"
user = "mcblog"
password = "123456"
db_name = "mcblog"

[qiniu]
access_key = "FQVAgztMfryIsmRoJ9qpwHKUny-o88v1KQE6yzUB"
secret_key = "2oY9gzWSx_aBCUZxEK-3KRPxOJcmOVxxlw9aO0DC"
bucket = "macleblog"
qiniu_server = "http://rx46effzx.hn-bkt.clouddn.com/"