jwtSecret = "myJWTSecret"

[server]
# "debug"开发模式；"release"生成模式
app_model = "debug"
app_port = ":8888"

[database]
host = "172.28.96.1"
port = "3306"
user = "mcblog"
password = "123456"
db_name = "mcblog"