jwtSecret = ""

[server]
# "debug"开发模式；"release"生成模式
app_model = "debug"
app_port = ":8888"

[database]
host = ""
port = ""
user = ""
password = ""
db_name = ""

[qiniu]
access_key = ""
secret_key = ""
bucket = ""
qiniu_server = ""
