# JWT 密钥
jwtSecret = ""

[server]
# "debug"开发模式；"release"生产模式
app_model = "debug"
app_port = ":8888"

# Mysql数据库配置
[database]
host = ""
port = ""
user = ""
password = ""
db_name = ""
loc = "Asia%2FShanghai" # GORM时区设置

# 七牛云对象存储配置
[qiniu]
access_key = ""
secret_key = ""
bucket = ""
qiniu_server = ""
region = ''  # 空间对应的机房，可选值Huadong、Huanan、Huabei、Beimei、Xinjiapo、ShouEr1、Zhejiang2
use_https = false  # 是否使用https域名
use_cdn_domains = false  # 上传是否使用CDN上传加速