package errno

const (
	SUCCESS = 200
	ERROR   = 500

	//code=1000...用户模块错误
	ERROR_USERNAME_USED    = 1001
	ERROR_PASSWORD_WRONG   = 1002
	ERROR_USER_NOT_EXIST   = 1003
	ERROR_TOKEN_NOT_EXIST  = 1004
	ERROR_TOKEN_TIMEOUT    = 1005
	ERROR_TOKEN_WRONG      = 1006
	ERROR_TOKEN_TYPE_WRONG = 1007
	ERROR_AUTH_DEFICIENT   = 1008
	//code=2000... 文章模块错误
	ERROR_ARTICLE_NOT_EXIST = 2001
	//code=3000... 分类模块错误
	ERROR_CATE_USED      = 3001
	ERROR_CATE_NOT_EXIST = 3002
	//code=4000... 标签模块错误
	ERROR_TAG_USED      = 4001
	ERROR_TAG_NOT_EXIST = 4002
)

var codemsg = map[int]string{
	SUCCESS: "OK",
	ERROR:   "FAIL",

	ERROR_USERNAME_USED:    "用户名已存在",
	ERROR_PASSWORD_WRONG:   "密码错误",
	ERROR_USER_NOT_EXIST:   "用户不存在",
	ERROR_TOKEN_NOT_EXIST:  "TOKEN不存在",
	ERROR_TOKEN_TIMEOUT:    "TOKEN已过期",
	ERROR_TOKEN_WRONG:      "TOKEN错误",
	ERROR_TOKEN_TYPE_WRONG: "TOKEN格式错误",
	ERROR_AUTH_DEFICIENT:   "权限不足",

	ERROR_CATE_USED:      "该分类已存在",
	ERROR_CATE_NOT_EXIST: "该分类不存在",

	ERROR_TAG_USED:      "该标签已存在",
	ERROR_TAG_NOT_EXIST: "该标签不存在",

	ERROR_ARTICLE_NOT_EXIST: "文章不存在",
}
